name: Deployment
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install node JS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci | echo 'Dependencies installed...'
      - name: linting code 
        run: npm run lint | echo 'Linting code...'
      - name: building code
        run: npm run build
      - name: deploying code
        run: echo 'Deploying code ....'
