name: Deployment Exercise 1
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: lint code
        run: npm run lint | echo 'Linting code ...'
  Test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: test code
        run: npm test
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Deploy code
        run: echo 'Deploy code ....'
    
       
  
        
